In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/home/nmietcomp/studentperformance.csv")

In [3]:
df.describe

<bound method NDFrame.describe of    Student_ID          Name  Gender  Math_Score Science_Score Attendance_Rate  \
0         S01   Arjun Singh       M        85.0            78             92%
1         S02  Priay Sharma       F         NaN            82             85%
2         S03     Amit Khan    male        45.0            50            0.78
3         S04   Sneha Patil  Female        92.0            88             95%
4         S05     Rohan Das       M       150.0            42             NaN
5         S06           NaN       F        72.0            65             88%
6         S07    Vikram Rao       m        58.0     "Missing"             82%
7         S08   Ananya Iyer       F        64.0            70             90%
8         S09      Rahul J.       M         2.0            40             65%
9         S10    Meera Nair  Female        78.0            75             89%
10        S11   Karan Johar       M        88.0            84             91%
11        S12      Sara Ali       f        42.0            38             70%
12        S13      Varun D.    male        76.0            77             NaN
13        S14   Pooja Hegde       F        95.0            99             98%
14        S15      Ishan K.       M        55.0            60             0.8
15        S16      Riya Sen  female        68.0            62             84%
16        S17     Aditya R.       M       180.0            85             92%
17        S18       Neha K.       F        74.0            72             86%
18        S19        Sam V.    male        30.0            35             60%
19        S20       Tara S.       F        82.0            80            0.88
20        S21      Kabir S.       M        91.0            89             94%
21        S22      Kiara A.  Female        85.0            82             90%
22        S23      Sunny L.       M        40.0           NaN             75%
23        S24        Raj M.    male        65.0            67             82%
24        S25     Simran K.       F       200.0            95             96%
25        S26        Dev D.       M        70.0            68             85%
26        S27     Jhanvi K.  female        77.0            74            0.79
27        S28      Vicky K.       M         1.0            45             68%
28        S29    Katrina K.       F        89.0            91             93%
29        S30     Ranbir K.    male        84.0            82             90%
30        S31        Sid M.       M        73.0            70             87%
31        S32       Alia B.  Female        96.0            94             97%
32        S33      Ayush K.       M        52.0            48            0.72
33        S34      Kriti S.       F        79.0            77             88%
34        S35     Kartik A.    male        81.0            79             89%
35        S36      Bhumi P.  Female        66.0            63             82%
36        S37      Tiger S.       M       300.0            40             70%
37        S38      Disha P.       F        88.0            85             91%
38        S39     Pankaj T.       M        75.0           NaN            0.83
39        S40     Tapsee P.       F        83.0            81             89%
40        S41      Manoj B.    male        48.0            52             76%
41        S42      Vidya B.  Female        90.0            92             94%
42        S43   Rajkumar R.       M        62.0            58            0.81
43        S44    Radhika A.       F        71.0            69             86%
44        S45   Ayushman K.       M        80.0            78             88%

    Participation_Score
0                   8.0
1                   7.0
2                   5.0
3                   9.0
4                   4.0
5                   6.0
6                  15.0
7                   7.0
8                   3.0
9                   8.0
10                  7.0
11                  4.0
12                  6.0
13                 10.0
14                  5.0
15                  7.0
16                  9.0
17                  NaN
18                  2.0
19                  8.0
20                  9.0
21                  8.0
22                  5.0
23                  6.0
24                 10.0
25                  7.0
26                  6.0
27                  3.0
28                  9.0
29                  8.0
30                  NaN
31                 10.0
32                  4.0
33                  7.0
34                  8.0
35                  6.0
36                  5.0
37                  9.0
38                  7.0
39                  8.0
40                  5.0
41                  9.0
42                  6.0
43                  7.0
44                  8.0  >

In [4]:
df

,Student_ID,Name,Gender,Math_Score,Science_Score,Attendance_Rate,Participation_Score
0,S01,Arjun Singh,M,85.0,78,92%,8.0
1,S02,Priay Sharma,F,NaN,82,85%,7.0
2,S03,Amit Khan,male,45.0,50,0.78,5.0
3,S04,Sneha Patil,Female,92.0,88,95%,9.0
4,S05,Rohan Das,M,150.0,42,NaN,4.0
5,S06,NaN,F,72.0,65,88%,6.0
6,S07,Vikram Rao,m,58.0,"""Missing""",82%,15.0
7,S08,Ananya Iyer,F,64.0,70,90%,7.0
8,S09,Rahul J.,M,2.0,40,65%,3.0
9,S10,Meera Nair,Female,78.0,75,89%,8.0
10,S11,Karan Johar,M,88.0,84,91%,7.0
11,S12,Sara Ali,f,42.0,38,70%,4.0
12,S13,Varun D.,male,76.0,77,NaN,6.0
13,S14,Pooja Hegde,F,95.0,99,98%,10.0
14,S15,Ishan K.,M,55.0,60,0.8,5.0
15,S16,Riya Sen,female,68.0,62,84%,7.0
16,S17,Aditya R.,M,180.0,85,92%,9.0
17,S18,Neha K.,F,74.0,72,86%,NaN
18,S19,Sam V.,male,30.0,35,60%,2.0
19,S20,Tara S.,F,82.0,80,0.88,8.0
20,S21,Kabir S.,M,91.0,89,94%,9.0
21,S22,Kiara A.,Female,85.0,82,90%,8.0
22,S23,Sunny L.,M,40.0,NaN,75%,5.0
23,S24,Raj M.,male,65.0,67,82%,6.0
24,S25,Simran K.,F,200.0,95,96%,10.0
25,S26,Dev D.,M,70.0,68,85%,7.0
26,S27,Jhanvi K.,female,77.0,74,0.79,6.0
27,S28,Vicky K.,M,1.0,45,68%,3.0
28,S29,Katrina K.,F,89.0,91,93%,9.0
29,S30,Ranbir K.,male,84.0,82,90%,8.0
30,S31,Sid M.,M,73.0,70,87%,NaN
31,S32,Alia B.,Female,96.0,94,97%,10.0
32,S33,Ayush K.,M,52.0,48,0.72,4.0
33,S34,Kriti S.,F,79.0,77,88%,7.0
34,S35,Kartik A.,male,81.0,79,89%,8.0
35,S36,Bhumi P.,Female,66.0,63,82%,6.0
36,S37,Tiger S.,M,300.0,40,70%,5.0
37,S38,Disha P.,F,88.0,85,91%,9.0
38,S39,Pankaj T.,M,75.0,NaN,0.83,7.0
39,S40,Tapsee P.,F,83.0,81,89%,8.0
40,S41,Manoj B.,male,48.0,52,76%,5.0
41,S42,Vidya B.,Female,90.0,92,94%,9.0
42,S43,Rajkumar R.,M,62.0,58,0.81,6.0
43,S44,Radhika A.,F,71.0,69,86%,7.0
44,S45,Ayushman K.,M,80.0,78,88%,8.0

In [5]:
df.info

<bound method DataFrame.info of    Student_ID          Name  Gender  Math_Score Science_Score Attendance_Rate  \
0         S01   Arjun Singh       M        85.0            78             92%
1         S02  Priay Sharma       F         NaN            82             85%
2         S03     Amit Khan    male        45.0            50            0.78
3         S04   Sneha Patil  Female        92.0            88             95%
4         S05     Rohan Das       M       150.0            42             NaN
5         S06           NaN       F        72.0            65             88%
6         S07    Vikram Rao       m        58.0     "Missing"             82%
7         S08   Ananya Iyer       F        64.0            70             90%
8         S09      Rahul J.       M         2.0            40             65%
9         S10    Meera Nair  Female        78.0            75             89%
10        S11   Karan Johar       M        88.0            84             91%
11        S12      Sara Ali       f        42.0            38             70%
12        S13      Varun D.    male        76.0            77             NaN
13        S14   Pooja Hegde       F        95.0            99             98%
14        S15      Ishan K.       M        55.0            60             0.8
15        S16      Riya Sen  female        68.0            62             84%
16        S17     Aditya R.       M       180.0            85             92%
17        S18       Neha K.       F        74.0            72             86%
18        S19        Sam V.    male        30.0            35             60%
19        S20       Tara S.       F        82.0            80            0.88
20        S21      Kabir S.       M        91.0            89             94%
21        S22      Kiara A.  Female        85.0            82             90%
22        S23      Sunny L.       M        40.0           NaN             75%
23        S24        Raj M.    male        65.0            67             82%
24        S25     Simran K.       F       200.0            95             96%
25        S26        Dev D.       M        70.0            68             85%
26        S27     Jhanvi K.  female        77.0            74            0.79
27        S28      Vicky K.       M         1.0            45             68%
28        S29    Katrina K.       F        89.0            91             93%
29        S30     Ranbir K.    male        84.0            82             90%
30        S31        Sid M.       M        73.0            70             87%
31        S32       Alia B.  Female        96.0            94             97%
32        S33      Ayush K.       M        52.0            48            0.72
33        S34      Kriti S.       F        79.0            77             88%
34        S35     Kartik A.    male        81.0            79             89%
35        S36      Bhumi P.  Female        66.0            63             82%
36        S37      Tiger S.       M       300.0            40             70%
37        S38      Disha P.       F        88.0            85             91%
38        S39     Pankaj T.       M        75.0           NaN            0.83
39        S40     Tapsee P.       F        83.0            81             89%
40        S41      Manoj B.    male        48.0            52             76%
41        S42      Vidya B.  Female        90.0            92             94%
42        S43   Rajkumar R.       M        62.0            58            0.81
43        S44    Radhika A.       F        71.0            69             86%
44        S45   Ayushman K.       M        80.0            78             88%

    Participation_Score
0                   8.0
1                   7.0
2                   5.0
3                   9.0
4                   4.0
5                   6.0
6                  15.0
7                   7.0
8                   3.0
9                   8.0
10                  7.0
11                  4.0
12                  6.0
13                 10.0
14                  5.0
15                  7.0
16                  9.0
17                  NaN
18                  2.0
19                  8.0
20                  9.0
21                  8.0
22                  5.0
23                  6.0
24                 10.0
25                  7.0
26                  6.0
27                  3.0
28                  9.0
29                  8.0
30                  NaN
31                 10.0
32                  4.0
33                  7.0
34                  8.0
35                  6.0
36                  5.0
37                  9.0
38                  7.0
39                  8.0
40                  5.0
41                  9.0
42                  6.0
43                  7.0
44                  8.0  >

In [6]:
df.head(10)

,Student_ID,Name,Gender,Math_Score,Science_Score,Attendance_Rate,Participation_Score
0,S01,Arjun Singh,M,85.0,78,92%,8.0
1,S02,Priay Sharma,F,NaN,82,85%,7.0
2,S03,Amit Khan,male,45.0,50,0.78,5.0
3,S04,Sneha Patil,Female,92.0,88,95%,9.0
4,S05,Rohan Das,M,150.0,42,NaN,4.0
5,S06,NaN,F,72.0,65,88%,6.0
6,S07,Vikram Rao,m,58.0,"""Missing""",82%,15.0
7,S08,Ananya Iyer,F,64.0,70,90%,7.0
8,S09,Rahul J.,M,2.0,40,65%,3.0
9,S10,Meera Nair,Female,78.0,75,89%,8.0

In [7]:
df.isnull().sum()

Student_ID             0
Name                   1
Gender                 0
Math_Score             1
Science_Score          2
Attendance_Rate        2
Participation_Score    2
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.fillna(df.mean(numeric_only=True),inplace=True)

In [10]:
df

,Student_ID,Name,Gender,Math_Score,Science_Score,Attendance_Rate,Participation_Score
0,S01,Arjun Singh,M,85.000000,78,92%,8.000000
1,S02,Priay Sharma,F,81.409091,82,85%,7.000000
2,S03,Amit Khan,male,45.000000,50,0.78,5.000000
3,S04,Sneha Patil,Female,92.000000,88,95%,9.000000
4,S05,Rohan Das,M,150.000000,42,NaN,4.000000
5,S06,NaN,F,72.000000,65,88%,6.000000
6,S07,Vikram Rao,m,58.000000,"""Missing""",82%,15.000000
7,S08,Ananya Iyer,F,64.000000,70,90%,7.000000
8,S09,Rahul J.,M,2.000000,40,65%,3.000000
9,S10,Meera Nair,Female,78.000000,75,89%,8.000000
10,S11,Karan Johar,M,88.000000,84,91%,7.000000
11,S12,Sara Ali,f,42.000000,38,70%,4.000000
12,S13,Varun D.,male,76.000000,77,NaN,6.000000
13,S14,Pooja Hegde,F,95.000000,99,98%,10.000000
14,S15,Ishan K.,M,55.000000,60,0.8,5.000000
15,S16,Riya Sen,female,68.000000,62,84%,7.000000
16,S17,Aditya R.,M,180.000000,85,92%,9.000000
17,S18,Neha K.,F,74.000000,72,86%,6.976744
18,S19,Sam V.,male,30.000000,35,60%,2.000000
19,S20,Tara S.,F,82.000000,80,0.88,8.000000
20,S21,Kabir S.,M,91.000000,89,94%,9.000000
21,S22,Kiara A.,Female,85.000000,82,90%,8.000000
22,S23,Sunny L.,M,40.000000,NaN,75%,5.000000
23,S24,Raj M.,male,65.000000,67,82%,6.000000
24,S25,Simran K.,F,200.000000,95,96%,10.000000
25,S26,Dev D.,M,70.000000,68,85%,7.000000
26,S27,Jhanvi K.,female,77.000000,74,0.79,6.000000
27,S28,Vicky K.,M,1.000000,45,68%,3.000000
28,S29,Katrina K.,F,89.000000,91,93%,9.000000
29,S30,Ranbir K.,male,84.000000,82,90%,8.000000
30,S31,Sid M.,M,73.000000,70,87%,6.976744
31,S32,Alia B.,Female,96.000000,94,97%,10.000000
32,S33,Ayush K.,M,52.000000,48,0.72,4.000000
33,S34,Kriti S.,F,79.000000,77,88%,7.000000
34,S35,Kartik A.,male,81.000000,79,89%,8.000000
35,S36,Bhumi P.,Female,66.000000,63,82%,6.000000
36,S37,Tiger S.,M,300.000000,40,70%,5.000000
37,S38,Disha P.,F,88.000000,85,91%,9.000000
38,S39,Pankaj T.,M,75.000000,NaN,0.83,7.000000
39,S40,Tapsee P.,F,83.000000,81,89%,8.000000
40,S41,Manoj B.,male,48.000000,52,76%,5.000000
41,S42,Vidya B.,Female,90.000000,92,94%,9.000000
42,S43,Rajkumar R.,M,62.000000,58,0.81,6.000000
43,S44,Radhika A.,F,71.000000,69,86%,7.000000
44,S45,Ayushman K.,M,80.000000,78,88%,8.000000

In [11]:
df['Attendance_Rate'] = df['Attendance_Rate'].astype(str).str.replace('%', '')

In [12]:
df

,Student_ID,Name,Gender,Math_Score,Science_Score,Attendance_Rate,Participation_Score
0,S01,Arjun Singh,M,85.000000,78,92,8.000000
1,S02,Priay Sharma,F,81.409091,82,85,7.000000
2,S03,Amit Khan,male,45.000000,50,0.78,5.000000
3,S04,Sneha Patil,Female,92.000000,88,95,9.000000
4,S05,Rohan Das,M,150.000000,42,nan,4.000000
5,S06,NaN,F,72.000000,65,88,6.000000
6,S07,Vikram Rao,m,58.000000,"""Missing""",82,15.000000
7,S08,Ananya Iyer,F,64.000000,70,90,7.000000
8,S09,Rahul J.,M,2.000000,40,65,3.000000
9,S10,Meera Nair,Female,78.000000,75,89,8.000000
10,S11,Karan Johar,M,88.000000,84,91,7.000000
11,S12,Sara Ali,f,42.000000,38,70,4.000000
12,S13,Varun D.,male,76.000000,77,nan,6.000000
13,S14,Pooja Hegde,F,95.000000,99,98,10.000000
14,S15,Ishan K.,M,55.000000,60,0.8,5.000000
15,S16,Riya Sen,female,68.000000,62,84,7.000000
16,S17,Aditya R.,M,180.000000,85,92,9.000000
17,S18,Neha K.,F,74.000000,72,86,6.976744
18,S19,Sam V.,male,30.000000,35,60,2.000000
19,S20,Tara S.,F,82.000000,80,0.88,8.000000
20,S21,Kabir S.,M,91.000000,89,94,9.000000
21,S22,Kiara A.,Female,85.000000,82,90,8.000000
22,S23,Sunny L.,M,40.000000,NaN,75,5.000000
23,S24,Raj M.,male,65.000000,67,82,6.000000
24,S25,Simran K.,F,200.000000,95,96,10.000000
25,S26,Dev D.,M,70.000000,68,85,7.000000
26,S27,Jhanvi K.,female,77.000000,74,0.79,6.000000
27,S28,Vicky K.,M,1.000000,45,68,3.000000
28,S29,Katrina K.,F,89.000000,91,93,9.000000
29,S30,Ranbir K.,male,84.000000,82,90,8.000000
30,S31,Sid M.,M,73.000000,70,87,6.976744
31,S32,Alia B.,Female,96.000000,94,97,10.000000
32,S33,Ayush K.,M,52.000000,48,0.72,4.000000
33,S34,Kriti S.,F,79.000000,77,88,7.000000
34,S35,Kartik A.,male,81.000000,79,89,8.000000
35,S36,Bhumi P.,Female,66.000000,63,82,6.000000
36,S37,Tiger S.,M,300.000000,40,70,5.000000
37,S38,Disha P.,F,88.000000,85,91,9.000000
38,S39,Pankaj T.,M,75.000000,NaN,0.83,7.000000
39,S40,Tapsee P.,F,83.000000,81,89,8.000000
40,S41,Manoj B.,male,48.000000,52,76,5.000000
41,S42,Vidya B.,Female,90.000000,92,94,9.000000
42,S43,Rajkumar R.,M,62.000000,58,0.81,6.000000
43,S44,Radhika A.,F,71.000000,69,86,7.000000
44,S45,Ayushman K.,M,80.000000,78,88,8.000000

In [15]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Math_Score', 'Science_Score',
       'Attendance_Rate', 'Participation_Score'],
      dtype='object')

In [16]:
df['Gender'] = df['Gender'].str.upper().str[0]